### ISSUE TITLE
res.Body isn't being closed on successful request

### ISSUE THREAD

**Issue by cjoudrey** [cjoudrey/gluahttp#15]
> // The http Client and Transport guarantee that Body is always
> // non-nil, even on responses without a body or responses with
> // a zero-length body. It is the caller's responsibility to
> // close Body. The default HTTP client's Transport does not
> // attempt to reuse HTTP/1.0 or HTTP/1.1 TCP connections
> // ("keep-alive") unless the Body is read to completion and is
> // closed.

It seems like we currently are not closing `res.Body` on successful request: https://github.com/cjoudrey/gluahttp/blob/9597a1d57575a0121726a2c50ad54fb74493a296/gluahttp.go#L189

**Comment by erikdubbelboer** [comment]
Thanks for reporting this issue, it is fixed now.

**Comment by erikdubbelboer** [comment]
And I just notice it's you who created the issue. I thought it was someone else :)

**Comment by cjoudrey** [comment]
It's actually someone who reported it via e-mail. :)

Thanks for the fix.
